### ISSUE TITLE
Compile errors on Travis

### ISSUE THREAD

**Issue by mattdowle** [eddelbuettel/rcppcctz#13]
I just added nanotime to fwrite.  It's passing fine on AppVeyor but I'm seeing these errors on Travis with RcppCCTZ it seems.  Any ideas?  Thanks.

https://travis-ci.org/Rdatatable/data.table/builds/196107129#L2805

**Comment by eddelbuettel** [comment]
What compiler is used in the failing test?

Anything older than g++ 4.9 is likely insufficient, so it won't fit your matrix of going down to really old code.

**Comment by eddelbuettel** [comment]
Can you make the behaviour optional?  Maybe just Suggests: nanotime and when you cannot have RcppCCTZ, fall back to bit64 writes?

It's a huge can of worms with a respect to your desire to accomodate R 2.15 and old gcc.  I only know two libraries that do this and they both require C++11 or newer.

OTOH if it is just for writes in extended ISO8601 / RFC 3339 style ... maybe bite the bullet and implement it?  For reading and parsing it is a while another can of worms.

**Comment by mattdowle** [comment]
Travis is testing with latest R and standard Ubuntu repo gcc, afaik.  (Aside: dependency of data.table is R 3.0.0)

**Comment by eddelbuettel** [comment]
1.  Quoting the [Travis log](https://travis-ci.org/Rdatatable/data.table/builds/196107129#L123): `gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3`
2.  Travis is stone old, default is a rather jurassic Ubuntu 12.04 ("precise").  Years ago I switched all mine to  Ubuntu 14.04 ("trusty") as one can.  What do you use?
3.  If you need newer compilers you can get them in different PPAs and/or the distro.
4.  Worst case, just read [my `.travis.yml` for RcppCCTZ](https://github.com/eddelbuettel/rcppcctz/blob/master/.travis.yml) which obviously builds it.

In sum, we really do need g++ 4,9 as I said we do.  CCTZ puts that burden on us.   I should have realized that sooner. 

You could also install a binary RcppCCTZ package to make Travis pass.  I could try to create you one.  That is generally my fallback as I am too impatient to build dependencies from source.

**Comment by eddelbuettel** [comment]
Where do you think this leaves us?  Do we need to bite the bullet and write plain ISO8601 versions of `strftime` and `strptime`, or say maybe extend [fasttime](https://cran.r-project.org/web/packages/fasttime/index.html) to do nanos?

**Comment by mattdowle** [comment]
Adding `dist: trusty` to data.table's `.travis.yml` solved it first time!  Passing Travis now.  It is now using gcc 4.8.4 and that appears to work fine.  I didn't know Travis was so old by default.
**Thanks!**
