### ISSUE TITLE
How  to actually link to cctz from external package?

### ISSUE THREAD

**Issue by vspinu** [eddelbuettel/rcppcctz#21]
Sorry for spaming today but what is the correct way to link to cctz? Contrary to what they claim cctz is not headers only, so how do I correctly link to it? 

Simply having LinkingTo: RcppCCTZ is not enough. I am getting:

```
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/vspinu/.lib/R/lubridate/libs/lubridate.so':
  /home/vspinu/.lib/R/lubridate/libs/lubridate.so: undefined symbol: _ZNK4cctz9time_zone6lookupERKNS_6detail10civil_timeINS1_10second_tagEEE
Error: loading failed
```

Naturally, cctz object files are not there. So, should I include all relevant xxx.cc cctz files in the package just like you do in `rcppcctz`? Or there is a more elegant solution?

**Comment by eddelbuettel** [comment]
As a started, I could export the parse and format functions for you at the C level.  Would that help?

**Comment by vspinu** [comment]
Not really. I really need full CCTZ API. Would really help if you could somehow put an object archive into the include folder so that I can pull it with -lcctz from Makevars.

**Comment by eddelbuettel** [comment]
That is beyond the scope of this package and project.  Look at the line count of CCTZ and all the classes.  

I'd rather talk to upstream about to ensure the build is header only, if only for subsets.  Boost is similar.  You can use Boost date_time header-only for as long as you forgo string operations (either parsing or formatting or both).   

Here,  I went to CCTZ to get the parsing and formatting explicitly so I don't mind the fact that the package itself is linking.

But in general you can't "just" assume a C++ library from another R package.  Once you are at the linking stage you are in the hands of the OS.   Now, carefully done header libraries can help here.  Maybe there is scope.   Talk to upstream -- it is not an RcppCCTZ issue.

**Comment by vspinu** [comment]
> That is beyond the scope of this package and project. Look at the line count of CCTZ and all the classes.

I actually meant to create an archive of compiled objects and keep it in RcppCCTZ path somewhere accessible. Something along these lines:

```Make

LIBCCTZ=cctz/time_tool.o \
   cctz/time_zone_fixed.o \
    cctz/time_zone_format.o \
    cctz/time_zone_if.o \
    cctz/time_zone_impl.o \
    cctz/time_zone_info.o \
    cctz/time_zone_libc.o \
    cctz/time_zone_lookup.o \
    cctz/time_zone_posix.o

$(SHLIB): libcctz.a

libcctz.a: $(LIBCCTZ)
	$(AR) rcs libcctz.a $(LIBCCTZ)
```

Then move libcctz.a into an accessible place. Isn't this doable?

**Comment by eddelbuettel** [comment]
I don't think I have seen this suggested, let alone, recommended on r-devel or in _Writing R Extension_.

**Comment by eddelbuettel** [comment]
I understood your question as asking whether the RcppCCTZ could provide the static library, and I still don't think so.

Compiling locally at your use for use in the same is possible.  That is closer to you embedding the sources yourself.  May still be brittle.
