### ISSUE TITLE
ERROR: compilation failed for package 'RcppCCTZ'

### ISSUE THREAD

**Issue by jariwalask** [eddelbuettel/rcppcctz#22]
Hi,
I'm trying to install RcppCCTZ 0.2.3 on RHEL 6.4 with R 3.4.0

And getting the following error messages.

> install.packages('RcppCCTZ')
Installing package into ‘/home/<user>/Rlibs’
(as ‘lib’ is unspecified)
trying URL 'http://cran.mtu.edu/src/contrib/RcppCCTZ_0.2.3.tar.gz'
Content type 'application/x-gzip' length 62869 bytes (61 KB)
==================================================
downloaded 61 KB

* installing *source* package ‘RcppCCTZ’ ...
** package ‘RcppCCTZ’ successfully unpacked and MD5 sums checked
** libs
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG  -I"/home/jari/Rlibs/bio3d/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG  -I"/home/jari/Rlibs/bio3d/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c civil_time_detail.cc -o civil_time_detail.o
In file included from civil_time_detail.cc:1:
../inst/include/civil_time_detail.h:37: error: expected nested-name-specifier before ‘year_t’
../inst/include/civil_time_detail.h:37: error: ‘year_t’ has not been declared
../inst/include/civil_time_detail.h:37: error: expected ‘;’ before ‘=’ token
../inst/include/civil_time_detail.h:37: error: expected unqualified-id before ‘=’ token
../inst/include/civil_time_detail.h:41: error: expected nested-name-specifier before ‘diff_t’
../inst/include/civil_time_detail.h:41: error: ‘diff_t’ has not been declared
../inst/include/civil_time_detail.h:41: error: expected ‘;’ before ‘=’ token
../inst/include/civil_time_detail.h:41: error: expected unqualified-id before ‘=’ token
../inst/include/civil_time_detail.h:46: error: expected nested-name-specifier before ‘month_t’
../inst/include/civil_time_detail.h:46: error: ‘month_t’ has not been declared
../inst/include/civil_time_detail.h:46: error: expected ‘;’ before ‘=’ token
../inst/include/civil_time_detail.h:46: error: expected unqualified-id before ‘=’ token
../inst/include/civil_time_detail.h:47: error: expected nested-name-specifier before ‘day_t’
../inst/include/civil_time_detail.h:47: error: ‘day_t’ has not been declared
../inst/include/civil_time_detail.h:47: error: expected ‘;’ before ‘=’ token
../inst/include/civil_time_detail.h:47: error: expected unqualified-id before ‘=’ token
../inst/include/civil_time_detail.h:48: error: expected nested-name-specifier before ‘hour_t’
../inst/include/civil_time_detail.h:48: error: ‘hour_t’ has not been declared
../inst/include/civil_time_detail.h:48: error: expected ‘;’ before ‘=’ token
../inst/include/civil_time_detail.h:48: error: expected unqualified-id before ‘=’ token
../inst/include/civil_time_detail.h:49: error: expected nested-name-specifier before ‘minute_t’
../inst/include/civil_time_detail.h:49: error: ‘minute_t’ has not been declared
../inst/include/civil_time_detail.h:49: error: expected ‘;’ before ‘=’ token
../inst/include/civil_time_detail.h:49: error: expected unqualified-id before ‘=’ token
../inst/include/civil_time_detail.h:50: error: expected nested-name-specifier before ‘second_t’
../inst/include/civil_time_detail.h:50: error: ‘second_t’ has not been declared
../inst/include/civil_time_detail.h:50: error: expected ‘;’ before ‘=’ token
../inst/include/civil_time_detail.h:50: error: expected unqualified-id before ‘=’ token
../inst/include/civil_time_detail.h:54: error: expected ‘)’ before ‘year’
../inst/include/civil_time_detail.h:78: error: ‘cctz::detail::impl::is_leap_year’ declared as an ‘inline’ variable
../inst/include/civil_time_detail.h:78: error: ‘year_t’ was not declared in this scope
../inst/include/civil_time_detail.h:78: error: expected ‘,’ or ‘;’ before ‘noexcept’
../inst/include/civil_time_detail.h:81: error: ‘cctz::detail::impl::year_index’ declared as an ‘inline’ variable
../inst/include/civil_time_detail.h:81: error: ‘year_t’ was not declared in this scope
../inst/include/civil_time_detail.h:81: error: ‘month_t’ was not declared in this scope
../inst/include/civil_time_detail.h:81: error: initializer expression list treated as compound expression
../inst/include/civil_time_detail.h:81: error: expected ‘,’ or ‘;’ before ‘noexcept’
../inst/include/civil_time_detail.h:84: error: ‘cctz::detail::impl::days_per_century’ declared as an ‘inline’ variable
../inst/include/civil_time_detail.h:84: error: ‘year_t’ was not declared in this scope
../inst/include/civil_time_detail.h:84: error: ‘month_t’ was not declared in this scope
../inst/include/civil_time_detail.h:84: error: initializer expression list treated as compound expression
../inst/include/civil_time_detail.h:84: error: expected ‘,’ or ‘;’ before ‘noexcept’
../inst/include/civil_time_detail.h:88: error: ‘cctz::detail::impl::days_per_4years’ declared as an ‘inline’ variable
../inst/include/civil_time_detail.h:88: error: ‘year_t’ was not declared in this scope
../inst/include/civil_time_detail.h:88: error: ‘month_t’ was not declared in this scope
../inst/include/civil_time_detail.h:88: error: initializer expression list treated as compound expression
../inst/include/civil_time_detail.h:88: error: expected ‘,’ or ‘;’ before ‘noexcept’
../inst/include/civil_time_detail.h:92: error: ‘cctz::detail::impl::days_per_year’ declared as an ‘inline’ variable
../inst/include/civil_time_detail.h:92: error: ‘year_t’ was not declared in this scope
../inst/include/civil_time_detail.h:92: error: ‘month_t’ was not declared in this scope
../inst/include/civil_time_detail.h:92: error: initializer expression list treated as compound expression
../inst/include/civil_time_detail.h:92: error: expected ‘,’ or ‘;’ before ‘noexcept’
../inst/include/civil_time_detail.h:95: error: ‘cctz::detail::impl::days_per_month’ declared as an ‘inline’ variable
../inst/include/civil_time_detail.h:95: error: ‘year_t’ was not declared in this scope
../inst/include/civil_time_detail.h:95: error: ‘month_t’ was not declared in this scope
../inst/include/civil_time_detail.h:95: error: initializer expression list treated as compound expression
../inst/include/civil_time_detail.h:95: error: expected ‘,’ or ‘;’ before ‘noexcept’
civil_time_detail.cc:72: error: expected ‘}’ at end of input
civil_time_detail.cc:72: error: expected ‘}’ at end of input
civil_time_detail.cc:72: error: expected ‘}’ at end of input
make: *** [civil_time_detail.o] Error 1
ERROR: compilation failed for package ‘RcppCCTZ’
* removing ‘/home/jari/Rlibs/bio3dweb/RcppCCTZ’

The downloaded source packages are in
	‘/tmp/RtmpHjN8UY/downloaded_packages’
Warning message:
In install.packages("RcppCCTZ") :
  installation of package ‘RcppCCTZ’ had non-zero exit status

**My sessionInfo()**

R version 3.4.0 (2017-04-21)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.4 (Santiago)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0

**Comment by eddelbuettel** [comment]
Can you remind me what g++ version you get on RHEL 6.4 ?  It may just be too old ...

**Comment by jariwalask** [comment]
You were right. Compilation worked with a [relatively] newer GCC.
```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
```
```
$ module load gcc/4.7.4
$ gcc --version
gcc (GCC) 4.7.4
```
And then
```
$ R --no-save -q
> install.packages('RcppCCTZ') #succeeds
```

Thanks for the quick response.

**Comment by eddelbuettel** [comment]
You may run into that problem with other R packages too as more and more now use (and require) C++11.

In that sense it is not a totally uncommon question.
