### ISSUE TITLE
FYI: CCTZ v2.0 is out, with some added features and spelling changes

### ISSUE THREAD

**Issue by devjgm** [eddelbuettel/rcppcctz#3]
Hi. I just wanted to let you know that we released a 2.0 version of https://github.com/google/cctz that adds a whole new civil-time library (for computing with human-scale time such as year, month, day, hour, minute, second). There are also some interface and spelling changes of the API points to make them match more standard C++ API (e.g., cctz::TimeZone -> cctz::time_zone). https://github.com/google/cctz/wiki/Migrating-from-V1-to-V2-interface has more info.

Anyway, I just wanted to let you know. Let us know if you run into any problems. Thanks.

**Comment by eddelbuettel** [comment]
Superb. Will take a look.
