### ISSUE TITLE
Minimal set of functions for C-level access by other packages

### ISSUE THREAD

**Issue by lsilvest** [eddelbuettel/rcppcctz#33]
I would be nice to have a small and coherent set of functions that allow this library to be accessed at C-level by other packages.

**Comment by eddelbuettel** [comment]
In particular because its wings have spread.  The whole of CCTZ, brought to CRAN by us first, is now copied three more times (!!).  Once in lubridate, and two more times and I forget where.

By exporting a small set of key functions (in a "80/20 rule" sens) we can maybey "prevent" further copies

**Comment by lsilvest** [comment]
Looking more in detail at `cctz`, it seems that 4 main functions are provided:

~~~ C++
template <typename D>
inline civil_second convert(const time_point<D>& tp, const time_zone& tz);

time_point<seconds> convert(const civil_second& cs, const time_zone& tz);

template <typename D>
std::string format(const std::string& fmt, const time_point<D>& tp, const time_zone& tz);

template <typename D>
bool parse(const std::string& fmt, const std::string& input, const time_zone& tz, time_point<D>* tpp);
~~~

`RcppCCTZ` provides versions of parse and format - at R level.

So I would suggest adding the lower-level `convert` functions at C level (possibly at R level too, but I'm not sure the mapping of `civil_time` can be done in a not-too-ugly way), and some versions of the existing format and parse at C level. The main difference at C level is that we need to provide the timezone as a string and then look it up; the rest can stay very similar).

With these 4 functions at C level, I believe `RcppCCTZ` would allow C code in other packages to access the essential functions of `cctz`.

**Comment by eddelbuettel** [comment]
Nice detective work.  I may have stayed away from the first two earlier because of the templated `time_point` which requires some thought.  But we can probably provide `double`-based `POSIXct`  converters and then go from there.

**Comment by lsilvest** [comment]
OK, so looking more in depth I found [this Stackoverflow answer](https://stackoverflow.com/a/42287094) in response to accessing C++ code in another package (see in particular the second part of the answer "the hard way").

The point, that I have tested, is that everything in the `./inst/include` and the library is available in fact to other packages at C level using a function like this one:

~~~ R
.libpath <- function() {
    cat(sprintf(
        "%s/RcppCCTZ/libs/RcppCCTZ%s",
        installed.packages()["RcppCCTZ","LibPath"][1],
        .Platform$dynlib.ext
    ))
}
~~~

And then configuring the `Makevars` and `Makevars.win` files in the client package to call that function like so:

~~~
PKG_LIBS += `${R_HOME}/bin/Rscript -e "cat(interface:::.libpath())"`
~~~

So it seems that there is no need for any modifications in `RcppCCTZ`, or possibly just supplying the `.libpath` function, although that is just a help. I was able to implement everything I wanted in the `nanotime` package without having to modify `RcppCCTZ`, so it looks that what was the aim of this issue is actually already fully available.

I'd be inclined to simply close this issue and use the above strategy...

**Comment by eddelbuettel** [comment]
I am not sure the required _linking_ will work reliably / easily / cross-platform.

We'd use this for way more cross-package collaboration if it was that easy.  I just think it isn't.

(Not that I'd want to argue with @nathan-russell who was a very fine contributor to Rcpp as well until he more or less disappeared...)

**Comment by lsilvest** [comment]
Yes, I see your point. I was able to get that to work both on Linux and Windows using a precompiled RcppCCTZ, so the exposure of the library is as expected not dependent on if it's locally compiled.

"In principle" (saying this with a huge amount of caution!) it should work. It seems to me, whatever the platform that the library has to be exposed for dynamic loading, so there should be a way to access it. That's the reasoning that pushed me to dig a bit more and find the answer by @nathan-russel.

Do you know of any reasonable way to test this and make sure it works on all platforms?

**Comment by eddelbuettel** [comment]
I am intrigued too I have to admit.  But see _e.g._ the (unanswered, AFAIK) post on r-package-devel about cross-shared-library execptions: another thing some of us learned the hard way as to avoid as a source of trouble.  I think we tried to above a loooong time and then relented.  

The thing the best way forward here would be a minimal sample package. You had identified four functions as exported from RcppCCTZ, so maybe cook up a baby package to access one or two.  We can then use RHub which lets us work with various Linux setup, Windows, macOS (!!) and even Slowlaris.  There is always an edge case, but we can try.

**Comment by lsilvest** [comment]
Thanks, will give it a try!

**Comment by lsilvest** [comment]
[The configure and cleanup](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Configure-and-cleanup) section of the [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) manual shows that there is quite some (hopefully portable) leeway writing packages for different platforms.

I have written a demo package `linktest` that accesses `RcppCCTZ`. I have found two methods that don't require any changes in the `RcppCCTZ` package:

1. Using a `configure` script to appropriately modify `Makevars` (necessary on MacOS); this can be found in [linktest's master branch](https://github.com/lsilvest/linktest)
2. Using the `install.libs.R` script to solve again the MacOS issue; this can be found in [linktests's branch install_libs](https://github.com/lsilvest/linktest/tree/install_libs)

Both have a `README` file that explains how they work, but the main issue is with MacOS and getting the correct shared library paths in `linktest.so`.

On Fedora I do get a NOTE, but not on Ubuntu, Windows or MacOS:
![Screenshot from 2019-10-08 23-22-04](https://user-images.githubusercontent.com/25395372/66449300-94569280-ea22-11e9-8534-fb6405d34e37.png)

Solaris compilation and install work, but `runTests.R` fails because `cctz`'s `load_time_zone` fails (which I believe is not news).

Finally, there is a third method that is probably more simple than the two above, and it consists of setting the `install_name` in `RcppCCTZ.so` when it is compiled, which makes the task of client packages such as `linktest` more simple. Obviously, the drawback here is having to modify a package on which one might not have control.

And the last question that remains is does this also work with pre-compiled packages. Any idea how I can test that? And is that a requirement for packages?

**Comment by eddelbuettel** [comment]
Wow.  Fabulous work. I need to catch up on the details.  I still fear that it is too much of a "free lunch" to be true but happy to be convinced otherwise.  Maybe something we should take to r-package-devel or r-devel?

The `otool` use on macOS seems similar to uses of `rpath` on Linux--the (needed) path for a shared library (not known to the system shared library linker) gets embedded in the file. Needless to say that will break once the reference library changes (or R changes major numbers, but we compile then anyway).

Great, great catch on the `install.libs.R` use. I had missed that one too.

**Comment by eddelbuettel** [comment]
Have a quick diff to make `linktest` pass `R CMD check --as-cran`; if you give me write access I can push else happy to send a PR.

**Comment by eddelbuettel** [comment]
Supposed CRAN asked us "well why don't you used the described, tested, and used mechanism for cross-package linking (and registration)", what would we say?  That this is "lighter" because it does not require registration and cooperation of the exporting package?   Can we say with (very straight) face that it is robust enough?

This is pretty amazeballs.  I wonder why we never tried this earlier.  Is `-ldl` new-ish?

**Comment by lsilvest** [comment]
Have given you access, thanks for the changes!

I believe that with the traditional mechanism one can't completely open the library and write code in the client package that directly instantiates classes and calls member functions. One can only provide a set of functions. Of course, if all the interface that one wants to make available is in header files, all this becomes a non issue and everything is available.

With the flexibility described in the "Writing R Extensions" it probably is possible to get `linktest` to compile anywhere. My main worry is that this might break when installing precompiled packages. I'm lacking some knowledge of the process there. I'll go to the source code and try to see what I can find out.

Because of the precompile issue, I would favour going with the "described, tested, and used" mechanisms. But this exercise is still somewhat interesting.

**Comment by eddelbuettel** [comment]
Ah, yes, sorry, you asked about precompiled. Skipped that.

The option moved from `build` to `INSTALL` IIRC.  I think you want `R CMD INSTALL --binary` which gets you a prebuilt one.  I would _suspect_ that _e.g._ on Linux you can mix and match clang and gcc here, but from what I here on macOS it is likely the same old issue of needing the same toolchain.

We could also use rhub to have artefacts built, and then downloaded and tested,

**Comment by lsilvest** [comment]
Thanks for the info, will have a look!

**Comment by eddelbuettel** [comment]
Definitely a good exercise.  I think we should take it to r-package-devel for review / comments.

**Comment by lsilvest** [comment]
Yes, it would be great to have additional insight.

**Comment by eddelbuettel** [comment]
Shall we present both, or just master, or just the branch?

**Comment by lsilvest** [comment]
I think both ideas are really similar, but the branch is a bit cleaner. I think the issues would be the same for both approaches, so probably presenting the branch and maybe just mentioning the `configure` method would be enough.

**Comment by eddelbuettel** [comment]
I agree.  Maybe flip master to 'initial-approach' or something like it, and make the current branch the 'master'?

**Comment by lsilvest** [comment]
Done.

**Comment by eddelbuettel** [comment]
This ticket can be closed as we now have this in file [inst/include.RcppCCTZ_API.h](https://github.com/eddelbuettel/rcppcctz/blob/master/inst/include/RcppCCTZ_API.h).
