### ISSUE TITLE
Parse error for dates without separator

### ISSUE THREAD

**Issue by Enchufa2** [eddelbuettel/rcppcctz#36]
This works:

```r
RcppCCTZ::parseDatetime("2019-09-30 2346", "%Y-%m-%d %H%M")
# [1] "2019-09-30 23:46:00 UTC"
```

And I believe this should work too:

```r
RcppCCTZ::parseDatetime("20190930 2346", "%Y%m%d %H%M")
# Error in RcppCCTZ::parseDatetime("20190930 2346", "%Y%m%d %H%M") : 
#   Parse error on 20190930 2346
```

**Comment by eddelbuettel** [comment]
We do a straight pass-through to the CCTZ parser so please check its documentation as to whether this is supported.  I can't remember if partial formats (no seconds, no subseconds, ...) work.  My examples all use something else.

**Comment by Enchufa2** [comment]
Then it must be an upstream bug, because it says

> Uses strftime()-like formatting options

And that's a perfectly valid strftime()-like format.

**Comment by eddelbuettel** [comment]
But it is not entirely `strftime`.  I use 

```r
parseDatetime("2016-12-07 10:11:12",        "\%Y-\%m-\%d \%H:\%M:\%S")   # full seconds
parseDatetime("2016-12-07 10:11:12.123456", "\%Y-\%m-\%d \%H:\%M:\%E*S") # fractional seconds
parseDatetime("2016-12-07T10:11:12.123456-00:00")  ## default RFC3339 format
```

in the help page.  Quuestions is whether dropping seconds is legit or not.  The `%E*S` always stuck me as not exactly plain `strftime` either but I never consulted a POSIX reference.

**Comment by Enchufa2** [comment]
Seconds are not the problem, the problem is the absence of a separator between year, month and day.

**Comment by eddelbuettel** [comment]
Yes, the separator may be required.

**Comment by Enchufa2** [comment]
Maybe in this case, but certainly not for `strptime`, `strftime` and the like.

**Comment by Enchufa2** [comment]
FYI, apparently this is because they don't assume that the year has four digits: https://github.com/google/cctz/issues/137#issuecomment-596662588

**Comment by eddelbuettel** [comment]
As I told you, "it's them".  All on purpose and for good reason, and they simply care less about char-by-char parity with the POSIX functions.  Which makes sense as they offer more.

**Comment by eddelbuettel** [comment]
This actually works with a slightly different (than `strptime`) format for which I just added a minimal use example in https://github.com/eddelbuettel/rcppcctz/commit/f81cda07c34089fae277f648ff69c16728d96bcb.
