### ISSUE TITLE
Header <R_ext/Rdynload.h> missing for RcppCCTZ_API.h, needed by R_GetCCallable.

### ISSUE THREAD

**Issue by kiwiwarmnfuzzy** [eddelbuettel/rcppcctz#41]
In RcppCCTZ_API.h, there's a reference to `R_GetCCallable`, which is defined in <R_ext/Rdynload.h> header. However, the header isn't in the #include lines of the header file or being included transitively by any of the existing header includes. 

The header would be more conformant to best practices if the <R_ext/Rdynload.h> is included.

**Comment by eddelbuettel** [comment]
That does sound reasonable.  Do you happen to an actual test case, ie a package _calling_ into this `RcppCCTZ_API.h` which exhibits this issue ie triggers a warning?

**Comment by eddelbuettel** [comment]
In practice this is not a concern at all as the header is included along with other header files -- see package [nanotime](https://github.com/eddelbuettel/nanotime) which has four source files including the header ... alongside `Rcpp.h` which brings the other things in.

**Comment by eddelbuettel** [comment]
So turns out that in `xtsAPI.h` in the xts had been doing just that: include this one header along with as few other headers.  `R.h` may be a bit broad so another suitable change may be to break it down from `R.h` to just the few headers that are actually needed.  Not sure I have another / better / smaller test case.

**Comment by eddelbuettel** [comment]
- I confused you re xts, it only has bearing here _as a model_ as that the first package I contributed such an export header to, and then added package RcppXts 
- nanotime is a client for this
- I also have include-what-you-use handy but it is a little complicated with R and other headers
- I would be up for actually expanding the PR to also replace including R.h with just what we need.  Interested?
- Overall this is good.  We use a function from it, so we should probably add the header as you suggest even if in almost all / all use case it comes in anyway.  But just being explicit has value so in favor.

**Comment by kiwiwarmnfuzzy** [comment]
About xts: Thanks for the clarification! I thought you were going to use add it as a dependency of the rcppcctz just to import R_ext/Rdynload.h header, which made me a little concerned as a user. But since you mentioned only as an example, I don't have much to say about it...

**Comment by kiwiwarmnfuzzy** [comment]
About replacing including R.h: Yep, I'm up for it. From what can see in [inst/include/RcppCCTZ_types.h](https://github.com/eddelbuettel/rcppcctz/blob/master/inst/include/RcppCCTZ_types.h), the <R.h> can be completely removed, and the only other type that needs additional #include is `int_fast64_t` from <cstdint>...
